framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: {}
        transports:
            download:
                dsn: '%env(resolve:MESSENGER_TRANSPORT_DSN)%'
                options:
                    path: '%kernel.project_dir%/.env'
                    project: D

        routing:
            'App\Message\Download': download
