###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    webserver:
        image: nginx:alpine
        container_name: youtube-dl-api-webserver
        volumes:
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
          - "8080:80"
        restart: always

    youtube-dl-api:
        build: docker/php-fpm
        container_name: youtube-dl-api-php-fpm
        restart: always
        volumes:
#          - ${VOLUME_DATA:?err}/youtube-dl:/opt/data/youtube-dl
          - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
