###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    webserver:
        image: nginx:alpine
        container_name: youtube-dl-api-webserver
        ports:
          - "${NGINX_PORT:-8080}:80"
        restart: always
        volumes:
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    youtube-dl-api:
        build: docker/php-fpm
        container_name: youtube-dl-api-php-fpm
        restart: always
        volumes:
          - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
