version: '3.8'

services:
    nginx:
        command: > 
          /bin/sh -c "export FASTCGI_PASS_HOST=youtube-dl-api SERVER_LISTEN_PORT=80 && 
            envsubst '$$FASTCGI_PASS_HOST $$SERVER_LISTEN_PORT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && 
            exec nginx -g 'daemon off;'"
        container_name: nginx
        depends_on:
          - youtube-dl-api
        ports:
          - ${YOUTUBE_DL_API_PUBLISHED_PORT:-8000}:80
        image: nginx:alpine
        restart: always
        volumes:
          - ./:/app:ro
          - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./docker/nginx/conf.d/default.template:/etc/nginx/conf.d/default.template

    youtube-dl-api:
        build:
            context: ./
            dockerfile: docker/Dockerfile
            args:
                VERSION: ${PHP_VERSION:-7.4}
            target: dev
        container_name: youtube-dl-api
        environment:
            SHELL_VERBOSITY: ${SHELL_VERBOSITY:-3}
        healthcheck:
            test: ["CMD-SHELL", "curl --fail -s 'http://nginx/monitor/health/checks' || exit 1"]
            start_period: 30s
            interval: 10s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
          - ./:/app:rw
